config/routes.rb
LocalS::Application.routes.draw do

  devise_for :users
  
  root :to => "wall#index"
  match ":slug/wall" => "wall#place", :as => 'place_wall'
  match "place/:id/new_note" => "places#new_note", :as => 'new_place_note'
  resources :notes
  resources :places
  resources :subscriptions

  match "api/save_location" => "users#save_location", :as => "api_save_location"
  match "api/get_local_notes" => "notes#get_local_notes", :as => "api_get_local_notes"

  namespace :messages do  
    match 'post_reply/:id' => "messages#post_reply", :as => 'post_reply'
    match 'inbox' => 'messages#recived_messages'
    match 'outbox' => 'messages#sent_messages'
    resources :messages
  end

  resources :comments

  namespace :users do
    match "update_profile" => "users#update"
    match "profile" => "users#my_profile"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :lat, :lng, :name, :round
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	default_scope order('created_at ASC')
	attr_accessible :content, :note_id, :user_id
	belongs_to :user
	belongs_to :note
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	geocoded_by :ip_address
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :receiver_id,  :title
  belongs_to :sender , :class_name => "User" , :foreign_key => "sender_id"
  belongs_to :receiver , :class_name => "User" , :foreign_key => "receiver_id"
  validates_presence_of :title, :content 

end

app/models/note.rb
class Note < ActiveRecord::Base
	default_scope order('created_at DESC')

  	attr_accessible :content, :latitude, :longitude, :place_id
  	belongs_to :user
  	belongs_to :place
  	has_many :comments

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :name, :private_view, :private_write, :lat, :lng
  belongs_to :user
  has_many :subscriptions
  has_many :notes
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :lat, :lng, :place_id, :round , :name
  belongs_to :user
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :notes
  has_many :comments
  geocoded_by :current_sign_in_ip
  # attr_accessible :title, :body

  has_many :sent_messages , :class_name => "Message" , :foreign_key => "sender_id"
  has_many :recived_messages , :class_name => "Message" , :foreign_key => "receiver_id"
  has_many :places
  has_many :subscriptions

  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :big => "600x400", :medium => "100x100>", :thumb => "42x42>" }, :default_url => "/assets/images/avatars/:style/default.jpg"

  def location_name
    begin
      s = Geocoder.search("#{self[:latitude]}, #{self[:longitude]}")
      s[0].formatted_address
    rescue
      'Location not available'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_guest
  before_filter :current_location

  #def get_location
  #	@current_location = request.location
  #end


  def current_location
    if user_signed_in?
      @lat = current_user.latitude
      @lng = current_user.longitude
    else
      @lat = @current_guest.latitude
      @lng = @current_guest.longitude
    end
  end

  def current_guest

  	if user_signed_in? and (current_user.updated_at < Time.now - 1.hour)
      #current_user.geocode
      #current_user.save
  	else

    	begin
    		@current_guest = Guest.find(session[:current_guest])
   	  rescue
   		 @current_guest = Guest.new
    		@current_guest.ip_address = request.remote_ip
    		@current_guest.geocode
    		@current_guest.save
    		session[:current_guest] = @current_guest.id
    	end

    end

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :authenticate_user!

	def create
		@comment = Comment.new(params[:comment])
		@comment.user = current_user
		@comment.save
		redirect_to root_path
	end

end

app/controllers/messages/messages_controller.rb
class Messages::MessagesController < ApplicationController
	before_filter :authenticate_user!
	def sent_messages
		@sent_messages = current_user.sent_messages		
	end

	def recived_messages
		@recived_messages = current_user.recived_messages.reverse
	end

	def post_reply
		@message = Message.new			
		@message.receiver = Note.find(params[:id]).user	
	end
	def create
		@message = Message.new(params[:message])
		@message.sender = current_user		
		if @message.save 
			redirect_to messages_inbox_path
		else
			render :post_reply 
		end

	end

	def destroy
		@message = Message.find(params[:id]).destroy
		redirect_to messages_inbox_path , :alert => "message deleted"
	rescue ActiveRecord::RecordNotFound
		redirect_to messages_inbox_path , :alert => "message not Found"
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	
	before_filter :authenticate_user!

	def new 
		@note = Note.new
	end

	def create 
		# this is a global wall note creator
		# for place note see places controller
		@note = Note.new(params[:note])
		@note.user = current_user
		if @note.latitude.nil? or @note.longitude.nil?
			@note.latitude = current_user.latitude
			@note.longitude = current_user.longitude
		end
		s = Geocoder.search([@note.latitude, @note.longitude])
		@note.address = s[0].formatted_address
		@note.save
		redirect_to root_path , :alert => "note created"
	end

	def get_local_notes
		@notes = Note.all
		render :json => @notes
	end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	before_filter :authenticate_user!

	def list
		
	end

	def new
		@place = Place.new
	end

	def create
		@place = Place.new(params[:place])
		@place.user = current_user
		@place.slug = @place.name.parameterize
		if !@place.save
			render new_subsciption_path
			return
		end
		@subscription = Subscription.new
		@subscription.place = @place
		@subscription.user = current_user
		@subscription.name = @place.name
		@subscription.save
		redirect_to root_path
	end

	def new_note
		@note = Note.new(params[:note])
		@note.user = current_user
		@note.save
		redirect_to place_wall_path(@note.place.slug) , :alert => "note created"
	end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@place = Place.new
		@places = Place.all
	end

end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

	before_filter :authenticate_user!

	def my_profile

	end

	def update
		@user = current_user
		@user.update_attributes(params[:user])
		@user.save
		redirect_to users_profile_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def save_location
		long = params[:long]
		lat = params[:lat]
		if user_signed_in?
			current_user.latitude = lat
			current_user.longitude = long
			current_user.save
			render :text => current_user.inspect
			return
		else
			guest = Guest.find(@current_guest.id)
			guest.latitude = lat
			guest.longitude = long
			guest.save
			render :text => guest.inspect
			return
		end
		render :nothing => true, :status => 200, :content_type => 'text/html'
	end

end

app/controllers/wall_controller.rb
class WallController < ApplicationController

	layout 'map', :only => "index"

	def index
		@notes = Note.all(:order => 'created_at DESC', :limit => 10)
		if user_signed_in?
			@new_note = Note.new
			@new_note.latitude = current_user.latitude
			@new_note.longitude = current_user.longitude
		end
	end

	def place
		@place = Place.where( :slug => params[:slug] ).first
		@notes = Note.where( :place_id => @place.id )
		if user_signed_in?
			@new_note = Note.new
			@new_note_form_url = new_place_note_path(@place)
			@new_note.place = @place
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/wall_helper.rb
module WallHelper
end

app/views/messages/messages/post_reply.html.erb
  	<%= form_for [:messages , @message ] , :style => "width:98.5%" do |f| %>

		<%= f.hidden_field :receiver_id %>
	<div class="note-content-container">

		<%= f.text_field :title ,:size => "" , :style => "width:98.5%" ,:placeholder=>"Write a title",required: true  %>
		<p>
			<%= f.text_area :content , :rows=> "" , :style => "width:98.5%; height:250px;" ,:placeholder=>"Write a note.." , required: true %>
		</p>
	</div>

	<div class="note-details-container">
			<div class="note-submit nav pull-right">
				<%= f.submit  "Send" , :class=>"btn btn-success"%>
			</div>
	</div>
	
	<% end %>
	<div class="clearfix"></div>
  

app/views/messages/messages/recived_messages.html.erb
<h1> Inbox </h1>

<table class="table table-striped">
              <thead>
                <tr>
                  <th class="time-message">Time</th>
                  <th class="title-message">Title</th>
                  <th>Content</th>
                  <th>Content</th>
                </tr>
              </thead>
              <tbody>
			<% @recived_messages.each do |mm| %>
                <tr>    
                <td><small style="font-size:10px;"><%= time_ago_in_words(mm.created_at) %> ago  </small>    </td>   
                  <td><%= mm.title %></td>
                  <td><%= mm.content %></td>
                  <td><%= link_to 'delete', messages_message_path(mm), :class => :btn, :data=>{:method=>:delete, :confirm=>"Are you sure?"} %></td>
                </tr>
             <% end %>
              </tbody>
            </table>

app/views/messages/messages/sent_messages.html.erb
<h1> Outbox </h1>

<table class="table table-striped">
              <thead>
                <tr>
                  <th class="time-message">Time</th>
                  <th class="title-message">Title</th>
                  <th>Content</th>
                  
                </tr>
              </thead>
              <tbody>
			<% @sent_messages.each do |mm| %>
                <tr>    
                <td><small style="font-size:10px;"><%= time_ago_in_words(mm.created_at) %> ago  </small>    </td>   
                  <td><%= mm.title %></td>
                  <td><%= mm.content %></td>
                </tr>
             <% end %>
              </tbody>
            </table>

app/views/notes/new.html.erb
<%= form_for @note do |f| %>
	<%= f.text_area :content , :placeholder => "Write note.." %>
	<%= f.submit 'add', :class => 'btn btn-success'  %>
<% end %>

app/views/subscriptions/new.html.erb
<h3>Create new place</h3>
<div class="pull-left">
	<%= form_for @place do |f| %>
		<input type="hidden" value="<%= current_user.latitude %>" name="place[lat]" />
		<input type="hidden" value="<%= current_user.longitude %>" name="place[lng]" />
		<p>
			<%= f.text_field :name, {:placeholder => "Place name"} %>
		</p>
		<p>
			<label>
				<%= f.check_box :private_write %>
				<span>Only me and invited people <br />can write posts and comments</span>
			</label>
		</p>
		<p>
			<label>
				<%= f.check_box :private_view %>
				<span>Only me and invited people <br />can see this place</span>
			</label>
		</p>	
		<p>
			<%= f.submit "Save & subscribe", {:class => 'btn btn-primary'} %>
		</p>
	<% end %>
</div>
<div class="pull-right">
	<div id="select-place-location-map" style="width: 400px; height:300px;"></div>
</div>
<div class="clearfix"></div>

<table class="table">

</table>

app/views/users/users/my_profile.html.erb
<h1>My profile</h1>
<%= form_for current_user, :url => users_update_profile_path do |f| %>
<table class="table">
	<tr>
		<td>Email</td>
		<td><%= current_user.email %></td>
	</tr>
	<tr>
		<td>Posts</td>
		<td><%= current_user.notes.size %></td>
	</tr>
	<tr>
		<td>Comments</td>
		<td><%= current_user.comments.size %></td>
	</tr>
	<tr>
		<td>Avatar</td>
		<td><%= image_tag current_user.avatar.url(:medium) %></td>
	</tr>
	<tr>
		<td>Change avatar</td>
		<td>
			<%= f.file_field :avatar %>
		</td>
	</tr>
	<tr>
		<td>
		</td>
		<td>
			<%= f.submit "Save", {:class => 'btn btn-primary'} %>
		</td>
	</tr>
</table>
<% end %>

app/views/wall/_categories.html.erb
<ul id="categories-menu">
		<li <% if current_page?(root_path) %>class="active"<% end %>><a href="<%= url_for root_path %>">Nearby</a></li>
	<% if user_signed_in? %>
	<% for category in current_user.subscriptions %>
		<% if !category.place.nil? %>
			<li <% if current_page?(place_wall_path(category.place.slug)) %>class="active"<% end %>>
				<a href="<%= url_for place_wall_path(category.place.slug) %>">
					<span class="label label-warning">2</span> <%= category.name %> 
				</a>
			</li>
		<% end %>
	<% end %>
	<% end %>
	<% if !current_page?( new_subscription_path ) %>
		<li class="new-category"><a href="<%= url_for new_subscription_path %>"><i class="icon-plus"></i> Add category</a></li>
	<% end %>
</ul>

app/views/wall/_new_post.html.erb
<div id="new-post-form">
	<%= form_for @new_note, :url => @new_note_form_url do |f| %>
		<div class="note-content-container">
			<textarea class="note-content" id="note_content" name="note[content]" placeholder="Write a note.."></textarea>
		</div>
		<div class="note-details-container">
			<%= f.hidden_field :latitude %>
			<%= f.hidden_field :longitude %>
			<%= f.hidden_field :place_id %>
			<div class="note-submit">
				<a href="#" class="button-tooltip btn btn-small disabled post-submit-enter-mode" title="Enter submits post"><i class="icon-pencil"></i></a>
				<%= f.submit 'Post', :class => 'btn btn-primary btn-small'  %>
			</div>
			<div class="note-user-location">
				<% if @new_note.place.nil? %>
					<span span="note-user-location-label">Your location: </span><span class="user-current-location"><%= current_user.location_name %></span>
					<a href="#" data-lng="<%= current_user.longitude %>" data-lat="<%= current_user.latitude %>" class="note-change-location">Change my location</a>
				<% else %>
					<span span="note-user-location-label">Your location: </span><span class="user-current-location"><%= @new_note.place.name %></span>
				<% end %>
			</div>
			<div class="clearfix"></div>
		</div>
	<% end %>
</div>

app/views/wall/_notes.html.erb
<% @notes.each do |note| %>

	<div class="note note-<%= note.id %>">

		<div class="well well-large">
			
			<blockquote <% if note.user == current_user %>class="own-note"<% end %>>
				<%= image_tag note.user.avatar.url(:thumb), {:class => 'avatar-image'} %>
				<p><%= note.content %> </p>
				<small><%= time_ago_in_words(note.created_at) %> ago  <cite title="Source Title"><%= note.address %></cite></small> 
			</blockquote> 

			<div class="comments" id="note-<%= note.id %>-comments" style="display:none">
				<% for comment in note.comments %>
				<blockquote <% if comment.user == current_user %>class="own-comment"<% end %>>
					<%= image_tag comment.user.avatar.url(:thumb), {:class => 'avatar-image'} %>
					<%= comment.content %>
					<small><%= time_ago_in_words(comment.created_at) %> ago</small> 
				</blockquote>
				<% end %>
			</div> 

			<% unless note.comments.empty? %>
			<a href="#" class="btn pull-left btn-small note-show-comments" data-id="<%= note.id %>">
				<% if note.comments.size > 1 %>
					<%= note.comments.size %> Comments&nbsp; <i class="icon-comment"></i>
				<% else %>
					<%= note.comments.size %> Comment&nbsp; <i class="icon-comment"></i>
				<% end %>
			</a>
			<% end %>

			<div class="btn-group pull-right">

				<% if note.user != current_user %>
				<a class="btn btn-small" href="<%= url_for(messages_post_reply_path(note)) %>">
					<i class="icon-envelope"></i> 
					&nbsp;Priv
				</a>
				<% end %>

			  	<a class="btn btn-small note-modal-show-location" data-lng="<%= note.longitude %>" data-lat="<%= note.latitude %>" href="#">
			  		<i class="icon-eye-open"></i> &nbsp;Map
			  	</a>
			  	
			  	<a class="btn btn-small btn-warning note-add-comment" data-id="<%= note.id %>" href="#" >
			  		<i class="icon-share-alt"></i> &nbsp;Comment
			  	</a>

			</div>
			<div class="clearfix"></div>

	    </div>

		<div class="comment-box" id="note-<%= note.id %>-comment-box">
			<% if user_signed_in? %>
			<%= form_for Comment.new do |f| %>
				<input type="hidden" name="comment[note_id]" value="<%= note.id %>" />
				<div class="textarea-container">
					<textarea class="comment-content" name="comment[content]"></textarea>
				</div>

				<%= f.submit "Post", { :class => 'btn btn-small btn-primary pull-right' } %>
				<a href="#" class="button-tooltip btn btn-small pull-right disabled post-submit-enter-mode" title="Enter submits post"><i class="icon-pencil"></i></a>
				<div class="clearfix"></div>
			<% end %>
			<% else %>
				<p style="padding: 5px 15px; margin:0; font-size:12px;">You have to sign in before posting comments.</p>
			<% end %>
		</div>

	</div><!-- .note -->

<% end %>

app/views/wall/index.html.erb
<% if user_signed_in? %>
	<%= render :partial => 'new_post' %>
<% end %>
<%= render :partial => "notes" %>

app/views/wall/place.html.erb
<% if user_signed_in? %>
	<%= render :partial => 'new_post' %>
<% end %>
<%= render :partial => "notes" %>