config/routes.rb
LocalS::Application.routes.draw do

  devise_for :users
  
  root :to => "wall#index"
  match ":slug/wall" => "wall#place", :as => 'place_wall'
  match "place/:id/new_note" => "places#new_note", :as => 'new_place_note'
  resources :notes
  resources :places
  resources :subscriptions

  match "api/save_location" => "users#save_location", :as => "api_save_location"
  match "api/get_local_notes" => "notes#get_local_notes", :as => "api_get_local_notes"

  namespace :messages do  
    match 'post_reply/:id' => "messages#post_reply", :as => 'post_reply'
    match 'inbox' => 'messages#recived_messages'
    match 'outbox' => 'messages#sent_messages'
    resources :messages
  end

  resources :comments

  namespace :users do
    match "update_profile" => "users#update"
    match "profile" => "users#my_profile"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :lat, :lng, :name, :round
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	default_scope order('created_at ASC')
	attr_accessible :content, :note_id, :user_id
	belongs_to :user
	belongs_to :note
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	geocoded_by :ip_address
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :receiver_id,  :title
  belongs_to :sender , :class_name => "User" , :foreign_key => "sender_id"
  belongs_to :receiver , :class_name => "User" , :foreign_key => "receiver_id"
  validates_presence_of :title, :content 

end

app/models/note.rb
class Note < ActiveRecord::Base
	default_scope order('created_at DESC')

  	attr_accessible :content, :latitude, :longitude, :place_id
  	belongs_to :user
  	belongs_to :place
  	has_many :comments

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :name, :private_view, :private_write, :lat, :lng
  belongs_to :user
  has_many :subscriptions
  has_many :notes
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :lat, :lng, :place_id, :round , :name
  belongs_to :user
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :notes
  has_many :comments
  geocoded_by :current_sign_in_ip
  # attr_accessible :title, :body

  has_many :sent_messages , :class_name => "Message" , :foreign_key => "sender_id"
  has_many :recived_messages , :class_name => "Message" , :foreign_key => "receiver_id"
  has_many :places
  has_many :subscriptions

  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :big => "600x400", :medium => "100x100>", :thumb => "42x42>" }, :default_url => "/assets/images/avatars/:style/default.jpg"

  def location_name
    begin
      s = Geocoder.search("#{self[:latitude]}, #{self[:longitude]}")
      s[0].formatted_address
    rescue
      'Location not available'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_guest
  before_filter :current_location

  #def get_location
  #	@current_location = request.location
  #end


  def current_location
    if user_signed_in?
      @lat = current_user.latitude
      @lng = current_user.longitude
    else
      @lat = @current_guest.latitude
      @lng = @current_guest.longitude
    end
  end

  def current_guest

  	if user_signed_in? and (current_user.updated_at < Time.now - 1.hour)
      #current_user.geocode
      #current_user.save
  	else

    	begin
    		@current_guest = Guest.find(session[:current_guest])
   	  rescue
   		 @current_guest = Guest.new
    		@current_guest.ip_address = request.remote_ip
    		@current_guest.geocode
    		@current_guest.save
    		session[:current_guest] = @current_guest.id
    	end

    end

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :authenticate_user!

	def create
		@comment = Comment.new(params[:comment])
		@comment.user = current_user
		@comment.save
		redirect_to root_path
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	
	before_filter :authenticate_user!

	def new 
		@note = Note.new
	end

	def create 
		# this is a global wall note creator
		# for place note see places controller
		@note = Note.new(params[:note])
		@note.user = current_user
		if @note.latitude.nil? or @note.longitude.nil?
			@note.latitude = current_user.latitude
			@note.longitude = current_user.longitude
		end
		s = Geocoder.search([@note.latitude, @note.longitude])
		@note.address = s[0].formatted_address
		@note.save
		redirect_to root_path , :alert => "note created"
	end

	def get_local_notes
		@notes = Note.all
		render :json => @notes
	end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	before_filter :authenticate_user!

	def list
		
	end

	def new
		@place = Place.new
	end

	def create
		@place = Place.new(params[:place])
		@place.user = current_user
		@place.slug = @place.name.parameterize
		if !@place.save
			render new_subsciption_path
			return
		end
		@subscription = Subscription.new
		@subscription.place = @place
		@subscription.user = current_user
		@subscription.name = @place.name
		@subscription.save
		redirect_to root_path
	end

	def new_note
		@note = Note.new(params[:note])
		@note.user = current_user
		@note.save
		redirect_to place_wall_path(@note.place.slug) , :alert => "note created"
	end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@place = Place.new
		@places = Place.all
	end

end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

	before_filter :authenticate_user!

	def my_profile

	end

	def update
		@user = current_user
		@user.update_attributes(params[:user])
		@user.save
		redirect_to users_profile_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def save_location
		long = params[:long]
		lat = params[:lat]
		if user_signed_in?
			current_user.latitude = lat
			current_user.longitude = long
			current_user.save
			render :text => current_user.inspect
			return
		else
			guest = Guest.find(@current_guest.id)
			guest.latitude = lat
			guest.longitude = long
			guest.save
			render :text => guest.inspect
			return
		end
		render :nothing => true, :status => 200, :content_type => 'text/html'
	end

end

app/controllers/wall_controller.rb
class WallController < ApplicationController

	layout 'map', :only => "index"

	def index
		@notes = Note.all(:order => 'created_at DESC', :limit => 10)
		if user_signed_in?
			@new_note = Note.new
			@new_note.latitude = current_user.latitude
			@new_note.longitude = current_user.longitude
		end
	end

	def place
		@place = Place.where( :slug => params[:slug] ).first
		@notes = Note.where( :place_id => @place.id )
		if user_signed_in?
			@new_note = Note.new
			@new_note_form_url = new_place_note_path(@place)
			@new_note.place = @place
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/wall_helper.rb
module WallHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" style="position: static;" id="top-bar">

  <div class="navbar-inner">
    <div class="container">
      
      <a class="brand" href="<%= url_for root_path %>">LocalSpotted</a>
      <ul class="nav pull-left"> 


  <% if user_signed_in? %>
        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-envelope"></i><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="<%= url_for(messages_inbox_path ) %>">Inbox</a></li>
                          <li><a href="<%= url_for(messages_outbox_path ) %>">Outbox</a></li>                          
                        </ul>
                          <% end %>
                        </ul>    
       
        <ul class="nav pull-right">
          
          <% if user_signed_in? %>
              <li>
                <a href="<%= url_for(users_profile_path) %>"> <i class="icon-user"></i> My profile </a>
              </li>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>  
              </li>
            <% end %>
          
        </ul>
    </div>
  </div><!-- /navbar-inner -->
</div>
<div id="current-coordinates" data-lat="<%= @lat %>" data-lng="<%= @lng %>"></div>

app/views/layouts/_map.html.erb
<div id="local-map">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocalSpotted</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="modal-window-space"></div>
  <%= render :partial => '/layouts/header' %>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => '/wall/categories' %>
  </div>
  <div class="span7" id="wall-container">
    <div id="wall">
      <% unless notice.nil? %><p class="notice"><%= notice %></p><% end %>
      <% unless notice.nil? %><p class="alert"><%= alert %></p><% end %>
      <%= yield %>
    </div>
</div>
  <div class="span2">&nbsp;</div>
  <div class="clearfix"></div>
</div>

<script>
	function getLocation()
  	{
  		console.log('f:getLocation')
  		if (navigator.geolocation)
    	{
    		navigator.geolocation.getCurrentPosition(savePosition)
    	}
  	}
	function savePosition(position)
  	{
  		$.ajax({
  			url: "<%= url_for api_save_location_path %>",
  			data: {lat: position.coords.latitude, long: position.coords.longitude }
		}).done(function ( data ) {
  			console.log( data )
		})
  	}
  	$(document).ready( function() {
  		getLocation()
  	})
</script>
</body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocalSpotted</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "localmap" %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
</head>
<body>
<div id="modal-window-space"></div>
  <%= render :partial => '/layouts/header' %>
  <%= render :partial => '/layouts/map' %>
<div class="row-fluid">
  <div class="span3">
    <%= render :partial => '/wall/categories' %>
  </div>
  <div class="span7" id="wall-container">
    <div id="wall">
      <% unless notice.nil? %><p class="notice"><%= notice %></p><% end %>
      <% unless notice.nil? %><p class="alert"><%= alert %></p><% end %>
      <%= yield %>
    </div>
</div>
  <div class="span2">&nbsp;</div>
  <div class="clearfix"></div>
</div>

<script>
	function getLocation()
  	{
  		console.log('f:getLocation')
  		if (navigator.geolocation)
    	{
    		navigator.geolocation.getCurrentPosition(savePosition)
    	}
  	}
	function savePosition(position)
  	{
  		$.ajax({
  			url: "<%= url_for api_save_location_path %>",
  			data: {lat: position.coords.latitude, long: position.coords.longitude }
		}).done(function ( data ) {
  			console.log( data )
		})
  	}
  	$(document).ready( function() {
  		getLocation()
  	})
</script>
</body>
</html>